export const Users = [
    {
        id: 1,
        profilePicture: "/assets/person/1.jpeg",
        username: "Marta Oliveira",
    },
    {
        id: 2,
        profilePicture: "/assets/person/2.jpeg",
        username: "Kleber Santos",
    },
    {
        id: 3,
        profilePicture: "/assets/person/3.jpeg",
        username: "João Cardoso",
    },
    {
        id: 4,
        profilePicture: "/assets/person/4.jpeg",
        username: "Adriana Pereira",
    },
    {
        id: 5,
        profilePicture: "/assets/person/5.jpeg",
        username: "Roberta da Costa",
    },
    {
        id: 6,
        profilePicture: "/assets/person/6.jpeg",
        username: "Vitoría Gomes",
    },
    {
        id: 7,
        profilePicture: "/assets/person/7.jpeg",
        username: "Thiago Silva",
    },
    {
        id: 8,
        profilePicture: "/assets/person/8.jpeg",
        username: "Sophia Maia",
    },
    {
        id: 9,
        profilePicture: "/assets/person/9.jpeg",
        username: "Nathalia Paz",
    },
    {
        id: 10,
        profilePicture: "/assets/person/10.jpeg",
        username: "Clara Almeida",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Uma vez flamengo, sempre flamengo",
        photo: "/assets/post/1.jpeg",
        date: "5 min ago",
        userId: 1,
        like: 32,
        Comment: 9,
    },
    {
        id: 2,
        photo: "/assets/post/2.jpeg",
        date: "15 min ago",
        userId: 2,
        like: 2,
        Comment: 1,
    },
    {
        id: 3,
        desc: "Vai Palmeiras",
        photo: "/assets/post/3.jpeg",
        date: "5 min ago",
        userId: 3,
        like: 3,
        Comment: 5,
    },
    {
        id: 4,
        photo: "/assets/post/4.jpeg",

        date: "25 min ago",
        userId: 4,
        like: 22,
        Comment: 12,
    },
    {
        id: 5,
        desc: "Lorem ipsuim",
        photo: "/assets/post/5.jpeg",
        date: "35 min ago",
        userId: 5,
        like: 320,
        Comment: 90,
    },
    {
        id: 6,
        photo: "/assets/post/6.jpeg",
        date: "45 min ago",
        userId: 6,
        like: 24,
        Comment: 243,
    },
    {
        id: 7,
        desc: "Deixa o like",
        photo: "/assets/post/7.jpeg",
        date: "46 min ago",
        userId: 7,
        like: 54,
        Comment: 12,
    },
    {
        id: 8,
        photo: "/assets/post/8.jpeg",
        date: "55 min ago",
        userId: 8,
        like: 232,
        Comment: 49,
    },
    {
        id: 9,
        desc: "Voa mlk",
        photo: "/assets/post/9.jpeg",
        date: "55 min ago",
        userId: 9,
        like: 320,
        Comment: 90,
    },
    {
        id: 10,
        photo: "/assets/post/10.jpeg",
        date: "57 min ago",
        userId: 10,
        like: 54,
        Comment: 41,
    },
]